# -*- coding: utf-8 -*-
"""
Онтология предметной области: типы сущностей, отношения, словари терминов ru/en.
Типы: Material, Process, Equipment, Property, Location, Expert, Lab, Publication, Parameter
"""

ENTITY_TYPES = ["Material", "Process", "Equipment", "Property", "Experiment", "Facility", "Location", "Expert", "Lab", "Publication", "Parameter"]

RELATION_TYPES = {
    ("Process", "Material"): "uses_material",
    ("Material", "Process"): "processed_by",
    ("Process", "Equipment"): "performed_in",
    ("Process", "Parameter"): "operates_at_condition",
    ("Material", "Parameter"): "has_condition",
    ("Process", "Property"): "affects_property",
    ("Material", "Property"): "has_property",
    ("Experiment", "Material"): "uses_material",
    ("Experiment", "Process"): "studies_process",
    ("Experiment", "Equipment"): "performed_in",
    ("Experiment", "Property"): "produces_output",
    ("Experiment", "Publication"): "described_in",
    ("Experiment", "Facility"): "performed_in",
    ("Facility", "Location"): "located_in",
    ("Expert", "Publication"): "author_of",
    ("Expert", "Lab"): "member_of",
    ("Publication", "Location"): "concerns_location",
}
DEFAULT_RELATION = "related_to"

# Канонические сущности: canon -> (type, [синонимы ru/en, аббревиатуры])
# Все синонимы матчатся регистронезависимо, по границам слов, с учётом русских окончаний (стемминг-суффикс).
TERMS = {
    # ---------- Materials ----------
    "никель": ("Material", ["nickel", "ni", "никел"]),
    "медь": ("Material", ["copper", "cu", "медн", "меди", "медь"]),
    "кобальт": ("Material", ["cobalt", "co", "кобальт"]),
    "золото": ("Material", ["gold", "au", "золот"]),
    "серебро": ("Material", ["silver", "ag", "серебр"]),
    "платина": ("Material", ["platinum", "pt", "платин"]),
    "палладий": ("Material", ["palladium", "pd", "паллади"]),
    "МПГ": ("Material", ["мпг", "pgm", "pgms", "платиноид", "металлы платиновой группы", "platinum group metals"]),
    "железо": ("Material", ["iron", "fe", "желез"]),
    "сера": ("Material", ["sulfur", "sulphur", "сер[аы]", "серо"]),
    "штейн": ("Material", ["matte", "штейн"]),
    "файнштейн": ("Material", ["файнштейн", "converter matte"]),
    "шлак": ("Material", ["slag", "шлак"]),
    "католит": ("Material", ["catholyte", "católit", "католит"]),
    "анолит": ("Material", ["anolyte", "анолит"]),
    "электролит": ("Material", ["electrolyte", "электролит"]),
    "сульфаты": ("Material", ["sulfate", "sulphate", "сульфат"]),
    "хлориды": ("Material", ["chloride", "хлорид"]),
    "гипс": ("Material", ["gypsum", "гипс", "техногенный гипс"]),
    "кальций": ("Material", ["calcium", "ca", "кальци"]),
    "магний": ("Material", ["magnesium", "mg", "магни"]),
    "натрий": ("Material", ["sodium", "na", "натри"]),
    "SO2": ("Material", ["so2", "so₂", "диоксид серы", "сернистый газ", "сернистый ангидрид", "sulfur dioxide"]),
    "серная кислота": ("Material", ["sulfuric acid", "серн[ао]й кислот", "h2so4"]),
    "пентландит": ("Material", ["pentlandite", "пентландит"]),
    "халькопирит": ("Material", ["chalcopyrite", "халькопирит"]),
    "пирротин": ("Material", ["pyrrhotite", "пирротин"]),
    "никелевая руда": ("Material", ["nickel ore", "никелев[аоы][яйе] руд", "латерит", "laterite", "сапролит", "лимонит"]),
    "медная руда": ("Material", ["copper ore", "медн[аоы][яйе] руд"]),
    "сульфидная руда": ("Material", ["sulfide ore", "сульфидн[аоы][яйе] руд"]),
    "концентрат": ("Material", ["concentrate", "концентрат"]),
    "хвосты": ("Material", ["tailings", "хвост[аоы]", "хвостохранилищ"]),
    "шахтная вода": ("Material", ["mine water", "шахтн[аоы][яйе] вод", "рудничн[аоы][яйе] вод"]),
    "сточные воды": ("Material", ["wastewater", "сточн[ыо][хе] вод", "сточные воды"]),
    "закладка": ("Material", ["backfill", "закладочн", "закладк"]),
    "угольные отходы": ("Material", ["coal waste", "угольн[ыо][хе] отход"]),
    "катод": ("Material", ["cathode", "катод"]),
    "анод": ("Material", ["anode", "анод"]),
    "шихта": ("Material", ["charge", "burden", "шихт"]),
    "аммиак": ("Material", ["ammonia", "аммиак"]),
    "известняк": ("Material", ["limestone", "известняк", "известь", "lime"]),
    "литий": ("Material", ["lithium", "li", "лити"]),
    "РЗЭ": ("Material", ["рзэ", "редкоземельн", "rare earth", "ree"]),
    # ---------- Processes ----------
    "выщелачивание": ("Process", ["leaching", "выщелачиван"]),
    "кучное выщелачивание": ("Process", ["heap leaching", "кучн[оы][гем]* выщелачиван", "кучное выщелачивание"]),
    "автоклавное выщелачивание": ("Process", ["pressure leaching", "autoclave leaching", "hpal", "автоклавн[оы][гем]* выщелачиван", "автоклавное окисление", "pox"]),
    "электроэкстракция": ("Process", ["electrowinning", "электроэкстракци", "электролиз", "electrolysis", "electrorefining", "электрорафинирован"]),
    "флотация": ("Process", ["flotation", "флотаци", "флотационн"]),
    "обогащение": ("Process", ["beneficiation", "обогащени", "обогатительн"]),
    "измельчение": ("Process", ["grinding", "milling", "измельчени"]),
    "плавка": ("Process", ["smelting", "плавк", "плавильн"]),
    "взвешенная плавка": ("Process", ["flash smelting", "взвешенн[аоы][яйе] плавк", "плавк[аи] во взвешенном состоянии"]),
    "конвертирование": ("Process", ["converting", "конвертирован"]),
    "обжиг": ("Process", ["roasting", "обжиг"]),
    "восстановление": ("Process", ["reduction", "восстановлени"]),
    "рафинирование": ("Process", ["refining", "рафинирован"]),
    "экстракция": ("Process", ["solvent extraction", "экстракци", "sx"]),
    "осаждение": ("Process", ["precipitation", "осаждени"]),
    "обессоливание": ("Process", ["desalination", "обессоливан", "деминерализаци", "demineralization"]),
    "обратный осмос": ("Process", ["reverse osmosis", "обратн[ыо][йм]* осмос", "ро мембран"]),
    "ионный обмен": ("Process", ["ion exchange", "ионн[ыо][йм]* обмен", "ионообменн"]),
    "очистка газов": ("Process", ["gas cleaning", "очистк[аи] газ", "газоочистк", "утилизаци[яи] so2", "улавливани"]),
    "очистка воды": ("Process", ["water treatment", "очистк[аи] вод", "водоочистк", "водоподготовк"]),
    "закачка в пласт": ("Process", ["deep well injection", "закачк", "захоронени[еяи] вод", "обратная закачка"]),
    "сгущение": ("Process", ["thickening", "сгущени"]),
    "фильтрация": ("Process", ["filtration", "фильтраци", "фильтрован"]),
    "сушка": ("Process", ["drying", "сушк"]),
    "гранулирование": ("Process", ["granulation", "гранулирован", "окомкован", "pelletizing"]),
    "брикетирование": ("Process", ["briquetting", "брикетирован"]),
    "хлорирование": ("Process", ["chlorination", "хлорирован", "хлорн[ао][ем]* выщелачиван"]),
    "цементация": ("Process", ["cementation", "цементаци"]),
    "гидрометаллургия": ("Process", ["hydrometallurgy", "гидрометаллург"]),
    "пирометаллургия": ("Process", ["pyrometallurgy", "пирометаллург"]),
    "биовыщелачивание": ("Process", ["bioleaching", "биовыщелачиван", "бактериальн[оы][ем]* выщелачиван"]),
    "аффинаж": ("Process", ["affinage", "аффинаж", "аффинирован"]),
    "циркуляция": ("Process", ["circulation", "циркуляци"]),
    "буровзрывные работы": ("Process", ["drilling and blasting", "буровзрывн", "взрывн[ыо][хе] работ"]),
    "закладочные работы": ("Process", ["backfilling", "закладочн[ыо][хе] работ"]),
    "проходка": ("Process", ["tunneling", "проходк", "проходческ"]),
    # ---------- Equipment ----------
    "печь взвешенной плавки": ("Equipment", ["пвп", "flash furnace", "flash smelting furnace", "печ[ьи] взвешенной плавки"]),
    "электропечь": ("Equipment", ["electric furnace", "электропеч", "руднотермическ[аоы][яйе] печ"]),
    "конвертер": ("Equipment", ["converter", "конвертер", "конвертор"]),
    "автоклав": ("Equipment", ["autoclave", "автоклав"]),
    "ванна электроэкстракции": ("Equipment", ["electrowinning cell", "ванн[аы] электроэкстракции", "электролизн[аоы][яйе] ванн", "электролизер"]),
    "диафрагменная ячейка": ("Equipment", ["diaphragm cell", "диафрагменн[аоы][яйе] ячейк", "диафрагм"]),
    "флотомашина": ("Equipment", ["flotation machine", "flotation cell", "флотомашин", "флотационн[аоы][яйе] машин", "флотокамер"]),
    "мельница": ("Equipment", ["mill", "мельниц"]),
    "дробилка": ("Equipment", ["crusher", "дробилк", "дроблени"]),
    "сгуститель": ("Equipment", ["thickener", "сгустител"]),
    "фильтр-пресс": ("Equipment", ["filter press", "фильтр-пресс", "пресс-фильтр"]),
    "скруббер": ("Equipment", ["scrubber", "скруббер"]),
    "рудоспуск": ("Equipment", ["ore pass", "рудоспуск"]),
    "ствол шахты": ("Equipment", ["mine shaft", "ствол[аы]* шахт", "шахтн[ыо][йм]* ствол"]),
    "насос": ("Equipment", ["pump", "насос"]),
    "мембрана": ("Equipment", ["membrane", "мембран"]),
    "анодная печь": ("Equipment", ["anode furnace", "анодн[аоы][яйе] печ"]),
    "миксер": ("Equipment", ["mixer", "миксер"]),
    "кристаллизатор": ("Equipment", ["crystallizer", "кристаллизатор"]),
    # ---------- Properties ----------
    "извлечение": ("Property", ["recovery", "extraction degree", "извлечени"]),
    "содержание": ("Property", ["grade", "content", "содержани"]),
    "концентрация": ("Property", ["concentration", "концентраци"]),
    "температура": ("Property", ["temperature", "температур"]),
    "давление": ("Property", ["pressure", "давлени"]),
    "скорость потока": ("Property", ["flow rate", "flow velocity", "скорост[ьи] поток", "скорост[ьи] циркуляции", "расход электролита"]),
    "плотность тока": ("Property", ["current density", "плотност[ьи] тока"]),
    "pH": ("Property", ["ph", "кислотност"]),
    "крупность": ("Property", ["particle size", "крупност", "гранулометрическ"]),
    "производительность": ("Property", ["capacity", "throughput", "производительност"]),
    "сухой остаток": ("Property", ["tds", "total dissolved solids", "сух[ои][йм]* остат[ок]", "солесодержани", "минерализаци"]),
    "напряжённо-деформированное состояние": ("Property", ["ндс", "stress-strain", "напряженно-деформированн", "напряжённо-деформированн"]),
    "удароопасность": ("Property", ["rockburst hazard", "удароопасн", "горн[ыо][йм]* удар"]),
    "устойчивость": ("Property", ["stability", "устойчивост"]),
    "прочность": ("Property", ["strength", "прочност"]),
    "выход металла": ("Property", ["metal yield", "выход[ао]* металл"]),
    "себестоимость": ("Property", ["operating cost", "capex", "opex", "себестоимост", "капитальн[ыо][хе] затрат", "эксплуатационн[ыо][хе] затрат"]),
    "энергопотребление": ("Property", ["energy consumption", "энергопотреблени", "расход электроэнергии"]),
    # ---------- Experiments ----------
    "эксперимент": ("Experiment", ["experiment", "experimental", "эксперимент", "опыт", "испытани", "серия опытов", "test work"]),
    "лабораторный опыт": ("Experiment", ["bench test", "laboratory test", "лабораторн[ыо][йм]* опыт", "лабораторн[ыо][йм]* эксперимент"]),
    "промышленное испытание": ("Experiment", ["pilot test", "plant trial", "промышленн[ыо][йм]* испытани", "опытно-промышленн"]),
    # ---------- Facilities ----------
    "обогатительная фабрика": ("Facility", ["processing plant", "concentrator", "обогатительн[аоы][яйе] фабрик", "обогатфабрик"]),
    "завод": ("Facility", ["plant", "factory", "smelter", "refinery", "завод", "комбинат"]),
    "рудник": ("Facility", ["mine", "рудник", "месторождени", "прииск"]),
    "цех": ("Facility", ["workshop", "shop", "цех"]),
    "полигон": ("Facility", ["site", "test site", "полигон", "площадк"]),
    # ---------- Locations ----------
    "Россия": ("Location", ["россия", "россии", "рф", "russia", "российск", "отечественн"]),
    "Норильск": ("Location", ["норильск", "нпр", "norilsk", "таймыр", "заполярн[ыо][йм]* филиал"]),
    "Кольский полуостров": ("Location", ["кольск", "мончегорск", "заполярный", "печенг", "kola"]),
    "Австралия": ("Location", ["австрали", "australia", "western australia"]),
    "Новая Каледония": ("Location", ["новая каледони", "новой каледони", "new caledonia", "goro", "koniambo", "коньямбо"]),
    "Чили": ("Location", ["чили", "chile"]),
    "Канада": ("Location", ["канад", "canada", "sudbury", "садбери"]),
    "Китай": ("Location", ["кита[йея]", "china", "китайск"]),
    "Индонезия": ("Location", ["индонези", "indonesia"]),
    "Финляндия": ("Location", ["финлянди", "finland", "harjavalta", "outokumpu"]),
    "ЮАР": ("Location", ["юар", "south africa", "южн[ао][йя] африк"]),
    "Казахстан": ("Location", ["казахстан", "kazakhstan"]),
    "холодный климат": ("Location", ["cold climate", "холодн[ыо][йм]* климат", "арктик", "arctic", "крайн[еи][гм]* север", "вечная мерзлот", "многолетнемерзл"]),
}

# Русские локации/термины, считающиеся "отечественной практикой"
DOMESTIC_LOCATIONS = {"Россия", "Норильск", "Кольский полуостров"}

# Единицы измерения для извлечения числовых параметров: regex-фрагменты
UNITS = [
    r"мг/дм ?3", r"мг/дм³", r"мг/л", r"г/л", r"г/дм ?3", r"г/дм³", r"г/т", r"кг/т", r"мг/м ?3", r"мг/м³",
    r"°\s?[CС]", r"град\.?\s?[CС]", r"градус", r"[КK](?=\b)",
    r"МПа", r"кПа", r"атм", r"бар",
    r"м/с", r"м/ч", r"м3/ч", r"м³/ч", r"л/мин", r"л/ч", r"дм3/мин",
    r"т/сут", r"т/год", r"тыс\.? ?т", r"млн ?т",
    r"А/м ?2", r"А/м²", r"кА",
    r"мВ", r"В(?=\b)",
    r"%", r"кВт·?ч", r"кВт", r"МВт",
    r"мкм", r"мм", r"см(?=\b)", r"м(?=\b)", r"км(?=\b)",
    r"мин(?=\b)", r"час(?:ов|а)?", r"ч(?=\b)", r"сут(?:ок)?",
    r"ppm", r"ppb", r"g/t", r"g/l", r"mg/l", r"t/d", r"t/a", r"kt", r"Mt", r"wt\.? ?%",
]

# Ключевые leader-слова темы для географической классификации публикации
FOREIGN_HINT = ["зарубежн", "мировая практика", "world practice", "abroad", "overseas", "international practice"]
